### ISSUE TITLE
Unable to detect application namespace

### ISSUE THREAD

**Issue by rupsk1607** [andersonef/RepositoriesPattern#2]
hi ,
im getting error while generating repository by given command.
php artisan make:repository BlogNamespace/Post --entity=Models/Post
"unable to detect application namespace"

kindly guide me where im missing.?
regards,
Rupal Gohel

**Comment by andersonef** [comment]
Hi @rupsk1607 

This happens because your entity must receive the complete namespace. Like this:

php artisan make:repository BlogNamespace/Post --entity=App/Models/Post

If you are using a custom application namespace, replace the App with your custom namespace.
Sorry but I think I really messed up when I wrote the docs.
Thanks for your insterest!

**Comment by rupsk1607** [comment]
many thanx it working now.
but it generate only with one method:
class PostRepository extends RepositoryAbstract{

```
public function entity()
{
    return \App\Models\Post::class;
}
```

}
i have downloaded demo code from below url, i wants to make repository code generate as per below.
https://github.com/bestmomo/laravel5-example/tree/master/app/Repositories

**Comment by andersonef** [comment]
This command generate two files for you. A service class and a repository class.
You will almost never need to change the repository class. Open the service class, localized at app/Services/YourService.php

That class extends AbstractService. This father class has some methods your class inherits, for example: create, update, destroy, find, all.. 
If you keep your service class without any change, in your controller you can do it:

function store(YourService $service, Request $req){
   return $service->create($req->all()); //it will work because the create method has been declared on father class (ServiceAbstract). 
}

You can also override the create method implementing your custom app logic, for example:

class YourService extends ServiceAbstract{

public function create(array $data){
    $obj = parent::create($data); 
    $obj->customProperty = 'something';
    $obj->save();
    return $obj;
}
}

In the repository class you can put your database manipulation logic. It looks like a database trigger. If you have some process you wanna do EVERY TIME a entity is saved or getted from database, you put this logic on repository.
Application logic is implemented on service class.
